export declare const typography_base: number;
export declare const fontFamily: string;
/******************************************************************************
 * Autogenerated styles. Only modify above this line.
 *****************************************************************************/
export declare const typography_scale: Array<number>;
